
let token='',state=null,dash=null;const $=id=>document.getElementById(id);async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+token,'Content-Type':'application/json'};const r=await fetch(path,opt);const d=await r.json();if(!r.ok)throw new Error(d.message||'Ошибка');return d}
async function login(){try{const d=await api('/api/admin/login',{method:'POST',headers:{},body:JSON.stringify({password:$('password').value})});token=d.token;localStorage.khva_admin=token;$('login').style.display='none';$('app').style.display='block';tab('dash');refreshAll()}catch(e){$('loginMsg').textContent=e.message}}
function logout(){localStorage.removeItem('khva_admin');location.reload()}async function refreshAll(){try{dash=await api('/api/admin/dashboard');const d=await api('/api/admin/state');state=d.state;renderDashboard();renderPlayers();renderSettings();fill();}catch(e){console.error(e)}}
function tab(x){document.querySelectorAll('.section').forEach(e=>e.classList.remove('active'));$(x).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.s===x));if(x==='audit')loadAudit();if(x==='notify')loadNotifications()}
function renderDashboard(){const s=dash.stats;$('stats').innerHTML=Object.entries(s).map(([k,v])=>`<div class="card"><div class="muted">${k}</div><div class="stat">${v}</div></div>`).join('');$('recent').innerHTML=(dash.recent_audit||[]).map(a=>`<div class="small"><b>${a.action}</b> — ${a.at} — ${a.actor||''} — ${a.reason||''}</div>`).join('')}
function renderPlayers(){if(!state)return;const q=($('playerSearch').value||'').toLowerCase();const ps=Object.values(state.players||{}).filter(p=>(p.player_id+' '+p.name).toLowerCase().includes(q));$('playerTable').innerHTML='<table class="table"><tr><th>ID</th><th>Имя</th><th>Баланс</th><th>Рейтинг</th><th>Уровень</th><th>Статус</th></tr>'+ps.slice(0,300).map(p=>`<tr><td>${p.player_id}</td><td>${p.name}</td><td>${p.coins}</td><td>${p.rating}</td><td>${p.level}</td><td>${p.banned?'<span class="bad">ЗАБЛОКИРОВАН</span>':'<span class="ok">Активен</span>'}</td></tr>`).join('')+'</table>'}
function renderSettings(){const s=state.settings||{};const fields=['maintenance_mode','global_announcement','global_reward_multiplier','play_cost','daily_bonus_amount','daily_mission_reward','weekly_mission_reward','return_bonus_base','return_bonus_per_day','return_bonus_max_days','rating_success','rating_level_up','starting_rating','default_language','default_quality','default_fps'];$('settingsForm').innerHTML=fields.map(k=>`<div class="field"><label>${k}</label><input id="set_${k}" value="${String(s[k]??'').replaceAll('"','&quot;')}"></div>`).join('')}
function fill(){for(const k of ['catalog','chests','missions','season','events','holidays','news'])$(k==='catalog'?'catalogJson':k+'Json').value=JSON.stringify(state[k],null,2);renderNewsAdmin();}
function renderNewsAdmin(){const list=$('newsListAdmin');if(!list||!state)return;list.innerHTML=(state.news||[]).slice().reverse().map(n=>`<div class="card"><div class="row"><span class="pill">${n.published===false?'ЧЕРНОВИК':'ОПУБЛИКОВАНА'}</span><b>${esc(n.title||'Без названия')}</b><span class="small muted">${n.publish_at||''}</span></div><div class="small" style="margin:8px 0">${esc(n.text||'')}</div><div class="row"><button class="btn" onclick="editNews('${n.id}')">Изменить</button><button class="btn" onclick="toggleNews('${n.id}',${n.published!==false})">${n.published===false?'Опубликовать':'Снять с публикации'}</button><button class="btn danger" onclick="deleteNews('${n.id}')">Удалить</button></div></div>`).join('')||'<div class="muted">Новостей пока нет</div>'}
function esc(x){return String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function editNews(id){const n=(state.news||[]).find(x=>x.id===id);if(!n)return;$('newsId').value=n.id;$('newsTitle').value=n.title||'';$('newsText').value=n.text||'';$('newsPublishAt').value=n.publish_at||'';tab('news')}
async function saveNews(publish){const payload={news:JSON.parse(JSON.stringify(state.news||[]))};const idv=$('newsId').value.trim();const title=$('newsTitle').value.trim();const text=$('newsText').value.trim();if(!title||!text)return alert('Заполните название и полный текст');let n=idv?payload.news.find(x=>x.id===idv):null;if(!n){n={id:'news_'+Date.now(),title:'',text:'',published:false,publish_at:'',notified:false,created_at:new Date().toISOString()};payload.news.push(n)}n.title=title;n.text=text;n.publish_at=$('newsPublishAt').value.trim();n.published=!!publish;if(!publish)n.notified=false;await saveState({news:payload.news,reason:publish?'Публикация/изменение новости':'Сохранение черновика новости'});$('newsMsg').textContent=publish?'Новость опубликована на сервере':'Черновик сохранён на сервере';editNews(n.id);renderNewsAdmin()}
async function toggleNews(id,published){const news=JSON.parse(JSON.stringify(state.news||[]));const n=news.find(x=>x.id===id);if(!n)return;n.published=!published;if(n.published&&!n.notified)n.notified=false;await saveState({news,reason:n.published?'Публикация новости':'Снятие новости с публикации'});renderNewsAdmin()}
async function deleteNews(id){id=id||$('newsId').value.trim();if(!id)return alert('Укажите ID новости');const news=(state.news||[]).filter(x=>x.id!==id);if(news.length===(state.news||[]).length)return alert('Новость не найдена');await saveState({news,reason:'Удаление новости'});$('newsId').value='';$('newsTitle').value='';$('newsText').value='';$('newsPublishAt').value='';renderNewsAdmin()}

async function saveSettings(){const s={...state.settings};for(const k of Object.keys(s)){const el=$('set_'+k);if(!el)continue;let v=el.value;if(v==='true')v=true;else if(v==='false')v=false;else if(v!==''&&!isNaN(Number(v)))v=Number(v);s[k]=v}await saveState({settings:s,reason:'Изменение экономики/настроек'});}
async function saveSection(k){try{const v=JSON.parse($(k==='catalog'?'catalogJson':k+'Json').value);await saveState({[k]:v,reason:'Изменение раздела '+k});}catch(e){alert('Ошибка JSON: '+e.message)}}
async function saveState(payload){try{await api('/api/admin/state',{method:'POST',body:JSON.stringify(payload)});await refreshAll();alert('Сохранено на сервере')}catch(e){alert(e.message)}}
async function playerAction(action){const idv=$('pid').value.trim();if(!idv)return alert('Укажите ID');const b={player_id:idv,action,reason:$('reason').value};if(action==='grant')b.reward={type:'coins',amount:Number(prompt('Сколько ₽ выдать?',100)||0)};if(action==='set_coins')b.coins=Number(prompt('Новый баланс ₽',0)||0);if(action==='set_rating')b.rating=Number(prompt('Новый рейтинг',0)||0);try{await api('/api/admin/player',{method:'POST',body:JSON.stringify(b)});$('playerMsg').textContent='Готово';refreshAll()}catch(e){$('playerMsg').textContent=e.message}}
async function sendNotification(){try{await api('/api/admin/notify',{method:'POST',body:JSON.stringify({player_id:$('ntarget').value||'all',kind:$('nkind').value,title:$('ntitle').value,message:$('nmessage').value,deliver_at:$('ndeliver').value,icon:$('nicon').value,reason:'Ручное уведомление'})});await loadNotifications();alert('Уведомление создано')}catch(e){alert(e.message)}}
async function loadNotifications(){try{const d=await api('/api/admin/notifications');$('notifications').innerHTML=(d.notifications||[]).map(n=>`<div class="card"><b>${n.title}</b><div>${n.message}</div><div class="small muted">${n.target} • ${n.kind} • ${n.deliver_at||'сразу'}</div></div>`).join('')}catch(e){}}
async function loadAudit(){try{const d=await api('/api/admin/audit?limit=500');$('auditData').textContent=JSON.stringify(d.audit,null,2);const t=await api('/api/admin/transactions');$('txData').innerHTML=(t.transactions||[]).slice(0,200).map(x=>`<div class="card"><b>${x.type}</b> • ${x.player_id}<div class="small muted">${x.at} • ${x.actor} • ${x.reason}</div><div class="row"><span class="pill">${x.reversed?'ОТМЕНЕНА':'АКТИВНА'}</span>${x.reversible&&!x.reversed?`<button class="btn danger" onclick="reverseTx('${x.id}')">Вернуть состояние</button>`:''}</div></div>`).join('')}catch(e){$('auditData').textContent=e.message}}
async function reverseTx(id){const reason=prompt('Причина отмены операции:','Возврат по решению администратора');if(!reason)return;try{await api('/api/admin/transaction/reverse',{method:'POST',body:JSON.stringify({transaction_id:id,reason})});await refreshAll();await loadAudit();alert('Операция отменена, состояние игрока возвращено')}catch(e){alert(e.message)}}
(function(){token=localStorage.khva_admin||'';if(token){$('login').style.display='none';$('app').style.display='block';tab('dash');refreshAll()}})();
